### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by ApiwatVVMT** [SirakisNg/CapstoneProject#2]
1) Follow lecture videos @ApiwatVVMT @Chawisa5757 @SirakisNg @Nattakol 
2) Develop the charts (blank template) @ApiwatVVMT @Chawisa5757 @Nattakol 
3) Login database @SirakisNg 
4) Connectivity PI server and back-end @SirakisNg 
5) Calculation (if needed) for each field on the dashboard @ApiwatVVMT @SirakisNg 
6) Link data to visualize on web page @SirakisNg

**Comment by SirakisNg** [comment]
I will start at review VDO and after I will make a login page
